// Kelimeler ve anlamları
const words = [
    { word: "ability", meaning: "yetenek" },
    { word: "accomplish", meaning: "başarmak" },
    { word: "advantage", meaning: "avantaj" },
    { word: "analyze", meaning: "analiz etmek" },
    { word: "approach", meaning: "yaklaşım" },
    { word: "attain", meaning: "ulaşmak" },
    { word: "attribute", meaning: "özellik" },
    { word: "awareness", meaning: "farkındalık" },
    { word: "benefit", meaning: "fayda" },
    { word: "capability", meaning: "kapasite" },
    { word: "capacity", meaning: "kapasite" },
    { word: "challenge", meaning: "meydan okuma" },
    { word: "change", meaning: "değişim" },
    { word: "characteristic", meaning: "özellik" },
    { word: "collaborate", meaning: "işbirliği yapmak" },
    { word: "communication", meaning: "iletişim" },
    { word: "competence", meaning: "yeterlilik" },
    { word: "comprehend", meaning: "anlamak" },
    { word: "concept", meaning: "kavram" },
    { word: "confidence", meaning: "güven" },
    { word: "consequence", meaning: "sonuç" },
    { word: "consideration", meaning: "düşünce" },
    { word: "consistently", meaning: "sürekli olarak" },
    { word: "construct", meaning: "inşa etmek" },
    { word: "contribute", meaning: "katkı sağlamak" },
    { word: "convince", meaning: "ikna etmek" },
    { word: "cooperate", meaning: "işbirliği yapmak" },
    { word: "coordination", meaning: "koordinasyon" },
    { word: "creative", meaning: "yaratıcı" },
    { word: "critical", meaning: "kritik" },
    { word: "decision", meaning: "karar" },
    { word: "deficiency", meaning: "eksiklik" },
    { word: "define", meaning: "tanımlamak" },
    { word: "degree", meaning: "derece" },
    { word: "demonstrate", meaning: "göstermek" },
    { word: "dependence", meaning: "bağımlılık" },
    { word: "describe", meaning: "tanımlamak" },
    { word: "design", meaning: "tasarlamak" },
    { word: "detail", meaning: "detay" },
    { word: "determine", meaning: "belirlemek" },
    { word: "development", meaning: "gelişim" },
    { word: "differentiate", meaning: "ayırt etmek" },
    { word: "difficult", meaning: "zor" },
    { word: "discover", meaning: "keşfetmek" },
    { word: "diverse", meaning: "çeşitli" },
    { word: "dynamic", meaning: "dinamik" },
    { word: "effective", meaning: "etkili" },
    { word: "efficient", meaning: "verimli" },
    { word: "elaborate", meaning: "detaylandırmak" },
    { word: "empathy", meaning: "empati" },
    { word: "empower", meaning: "yetkilendirmek" },
    { word: "enable", meaning: "olanak sağlamak" },
    { word: "encourage", meaning: "cesaretlendirmek" },
    { word: "enhance", meaning: "geliştirmek" },
    { word: "enthusiasm", meaning: "heves" },
    { word: "environment", meaning: "çevre" },
    { word: "equivalent", meaning: "eşdeğer" },
    { word: "evaluate", meaning: "değerlendirmek" },
    { word: "evolve", meaning: "gelişmek" },
    { word: "excellence", meaning: "mükemmellik" },
    { word: "exceptional", meaning: "olağanüstü" },
    { word: "experience", meaning: "deneyim" },
    { word: "expertise", meaning: "uzmanlık" },
    { word: "explore", meaning: "keşfetmek" },
    { word: "express", meaning: "ifade etmek" },
    { word: "facilitate", meaning: "kolaylaştırmak" },
    { word: "flexibility", meaning: "esneklik" },
    { word: "focus", meaning: "odaklanmak" },
    { word: "function", meaning: "fonksiyon" },
    { word: "fundamental", meaning: "temel" },
    { word: "generate", meaning: "üretmek" },
    { word: "global", meaning: "küresel" },
    { word: "growth", meaning: "büyüme" },
    { word: "guidance", meaning: "rehberlik" },
    { word: "handle", meaning: "üstesinden gelmek" },
    { word: "hierarchy", meaning: "hierarşi" },
    { word: "highlight", meaning: "vurgulamak" },
    { word: "identify", meaning: "tanımlamak" },
    { word: "imagination", meaning: "hayal gücü" },
    { word: "implement", meaning: "uygulamak" },
    { word: "improve", meaning: "geliştirmek" },
    { word: "incentive", meaning: "teşvik" },
    { word: "influence", meaning: "etki" },
    { word: "innovation", meaning: "yenilik" },
    { word: "insight", meaning: "kavrayış" },
    { word: "inspire", meaning: "ilham vermek" },
    { word: "integrate", meaning: "entegre etmek" },
    { word: "integrity", meaning: "dürüstlük" },
    { word: "interact", meaning: "etkileşimde olmak" },
    { word: "interpret", meaning: "yorumlamak" },
    { word: "intuition", meaning: "sezgi" },
    { word: "invent", meaning: "icat etmek" },
    { word: "investigate", meaning: "araştırmak" },
    { word: "involve", meaning: "içermek" },
    { word: "isolate", meaning: "izole etmek" },
    { word: "knowledge", meaning: "bilgi" },
    { word: "leadership", meaning: "liderlik" },
    { word: "learn", meaning: "öğrenmek" },
    { word: "leverage", meaning: "kaldıraç" },
    { word: "logical", meaning: "mantıklı" },
    { word: "maintain", meaning: "sürdürmek" },
    { word: "management", meaning: "yönetim" },
    { word: "mastery", meaning: "uzmanlık" },
    { word: "maximize", meaning: "maksimize etmek" },
    { word: "measure", meaning: "ölçmek" },
    { word: "mediate", meaning: "aracılık etmek" },
    { word: "method", meaning: "metot" },
    { word: "mindful", meaning: "dikkatli" },
    { word: "minimize", meaning: "en aza indirmek" },
    { word: "motivate", meaning: "motivasyon sağlamak" },
    { word: "negotiate", meaning: "pazarlık etmek" },
    { word: "network", meaning: "ağ" },
    { word: "observe", meaning: "gözlemlemek" },
    { word: "obtain", meaning: "elde etmek" },
    { word: "opportunity", meaning: "fırsat" },
    { word: "optimize", meaning: "optimize etmek" },
    { word: "organize", meaning: "düzenlemek" },
    { word: "original", meaning: "özgün" },
    { word: "outcome", meaning: "sonuç" },
    { word: "output", meaning: "çıktı" },
    { word: "outsource", meaning: "dış kaynak kullanmak" },
    { word: "overcome", meaning: "üstesinden gelmek" },
    { word: "overview", meaning: "genel bakış" },
    { word: "participate", meaning: "katılmak" },
    { word: "passionate", meaning: "coşkulu" },
    { word: "patience", meaning: "sabır" },
    { word: "pattern", meaning: "kalıp" },
    { word: "perceive", meaning: "algılamak" },
    { word: "perform", meaning: "performans sergilemek" },
    { word: "perseverance", meaning: "azim" },
    { word: "perspective", meaning: "perspektif" },
    { word: "planning", meaning: "planlama" },
    { word: "positive", meaning: "olumlu" },
    { word: "potential", meaning: "potansiyel" },
    { word: "practical", meaning: "pratik" },
    { word: "precise", meaning: "kesin" },
    { word: "predict", meaning: "tahmin etmek" },
    { word: "preparation", meaning: "hazırlık" },
    { word: "present", meaning: "sunmak" },
    { word: "prevent", meaning: "önlemek" },
    { word: "prioritize", meaning: "önceliklendirmek" },
    { word: "problem-solving", meaning: "problem çözme" },
    { word: "process", meaning: "süreç" },
    { word: "productivity", meaning: "verimlilik" },
    { word: "professionalism", meaning: "profesyonellik" },
    { word: "profitable", meaning: "kârlı" },
    { word: "progress", meaning: "ilerleme" },
    { word: "project", meaning: "proje" },
    { word: "promote", meaning: "tanıtmak" },
    { word: "proposal", meaning: "öneri" },
    { word: "prosperity", meaning: "refah" },
    { word: "provide", meaning: "sağlamak" },
    { word: "quality", meaning: "kalite" },
    { word: "quantity", meaning: "miktar" },
    { word: "questionnaire", meaning: "anket" },
    { word: "raise", meaning: "artırmak" },
    { word: "reaction", meaning: "reaksiyon" },
    { word: "realistic", meaning: "gerçekçi" },
    { word: "reassure", meaning: "güvence vermek" },
    { word: "recession", meaning: "durgunluk" },
    { word: "recognize", meaning: "tanımak" },
    { word: "recommend", meaning: "önermek" },
    { word: "reconcile", meaning: "uzlaştırmak" },
    { word: "recruit", meaning: "işe almak" },
    { word: "reduction", meaning: "azaltma" },
    { word: "reference", meaning: "referans" },
    { word: "refine", meaning: "iyileştirmek" },
    { word: "reflect", meaning: "yansıtmak" },
    { word: "reform", meaning: "reform yapmak" },
    { word: "refund", meaning: "geri ödeme" },
    { word: "refuse", meaning: "reddetmek" },
    { word: "regulation", meaning: "düzenleme" },
    { word: "reimburse", meaning: "geri ödemek" },
    { word: "reinforce", meaning: "güçlendirmek" },
    { word: "relationship", meaning: "ilişki" },
    { word: "reliable", meaning: "güvenilir" },
    { word: "reluctant", meaning: "isteksiz" },
    { word: "remarkable", meaning: "dikkate değer" },
    { word: "remuneration", meaning: "ücret" },
    { word: "renegotiate", meaning: "yeniden görüşmek" },
    { word: "renovate", meaning: "yenilemek" },
    { word: "repair", meaning: "tamir etmek" },
    { word: "reputation", meaning: "ün" },
    { word: "request", meaning: "istek" },
    { word: "require", meaning: "gerektirmek" },
    { word: "research", meaning: "araştırma" },
    { word: "reservation", meaning: "rezervasyon" },
    { word: "resignation", meaning: "istifa" },
    { word: "resolve", meaning: "çözmek" },
    { word: "resourceful", meaning: "yaratıcı" },
    { word: "respect", meaning: "saygı" },
    { word: "responsibility", meaning: "sorumluluk" },
    { word: "responsive", meaning: "duyarlı" },
    { word: "restoration", meaning: "restorasyon" },
    { word: "result", meaning: "sonuç" },
    { word: "retain", meaning: "korumak" },
    { word: "revenue", meaning: "gelir" },
    { word: "review", meaning: "inceleme" },
    { word: "revise", meaning: "gözden geçirmek" },
    { word: "risk", meaning: "risk" },
    { word: "role", meaning: "rol" },
    { word: "routine", meaning: "rutin" },
    { word: "rural", meaning: "kırsal" },
    { word: "salary", meaning: "maaş" },
    { word: "sales", meaning: "satış" },
    { word: "satisfaction", meaning: "memnuniyet" },
    { word: "schedule", meaning: "programlamak" },
    { word: "scope", meaning: "kapsam" },
    { word: "search", meaning: "aramak" },
    { word: "secure", meaning: "güvenli" },
    { word: "segment", meaning: "bölüm" },
    { word: "selection", meaning: "seçim" },
    { word: "self-esteem", meaning: "özsaygı" },
    { word: "sell", meaning: "satmak" },
    { word: "sense", meaning: "anlam" },
    { word: "sensitive", meaning: "duyarlı" },
    { word: "sentence", meaning: "cümle" },
    { word: "separate", meaning: "ayrı" },
    { word: "serious", meaning: "ciddi" },
    { word: "serve", meaning: "hizmet etmek" },
    { word: "setback", meaning: "başarısızlık" },
    { word: "settle", meaning: "yerleşmek" },
    { word: "severe", meaning: "şiddetli" },
    { word: "share", meaning: "paylaşmak" },
    { word: "shift", meaning: "değişim" },
    { word: "shortage", meaning: "kıtlık" },
    { word: "significance", meaning: "önem" },
    { word: "similar", meaning: "benzer" },
    { word: "simultaneously", meaning: "aynı anda" },
    { word: "simplify", meaning: "basitleştirmek" },
    { word: "skill", meaning: "beceri" },
    { word: "sluggish", meaning: "ağır işleyen" },
    { word: "smart", meaning: "zeki" },
    { word: "solution", meaning: "çözüm" },
    { word: "source", meaning: "kaynak" },
    { word: "specialist", meaning: "uzman" },
    { word: "specific", meaning: "belirli" },
    { word: "specify", meaning: "belirtmek" },
    { word: "spokesperson", meaning: "sözcü" },
    { word: "spread", meaning: "yayılmak" },
    { word: "stability", meaning: "istikrar" },
    { word: "standard", meaning: "standart" },
    { word: "start", meaning: "başlamak" },
    { word: "state", meaning: "durum" },
    { word: "statistics", meaning: "istatistik" },
    { word: "status", meaning: "durum" },
    { word: "stimulate", meaning: "uyarmak" },
    { word: "stop", meaning: "durmak" },
    { word: "strategy", meaning: "strateji" },
    { word: "strength", meaning: "güç" }
			// ve daha fazla kelime ...
		];

    const wordElement = document.getElementById("word");
    const meaningElement = document.getElementById("meaning");
    const buttonElement = document.getElementById("btn");

    function generateWord() {
      const randomIndex = Math.floor(Math.random() * words.length);
      const word = words[randomIndex];
      wordElement.innerText = word.word;
      meaningElement.innerText = word.meaning;
    }

    buttonElement.addEventListener("click", generateWord);

    generateWord();